apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo-infra-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/gpt14/argocd.git
      revision: main
      directories:
      - path: foo-infra/*/envs/dev
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}'
    spec:
      # The project the application belongs to.
      project: foo
      # Source of the application manifests
      source:
        repoURL: https://github.com/gpt14/argocd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      # Destination cluster and namespace to deploy the application
      destination:
        name: in-cluster
        namespace: foo
